### ISSUE TITLE
A new try to also port definitions inside classes whenever possible.

### ISSUE THREAD

**Issue by bluedxca93** [bluedxca93/18-20#2]
```

echo normal gtk_range_width'=''"'`sed '/[*] [{]/!d;s//\n/;s/.*\n//;ta;:a;s/[}].*$//;tb;$!{n;ba};:b;/^$/d' $1 | grep -i GtkRange-slider-width | tr -cd '[[:digit:]]'`'"'

echo normal_gtk_stepper_size'=''"'`sed '/[*] [{]/!d;s//\n/;s/.*\n//;ta;:a;s/[}].*$//;tb;$!{n;ba};:b;/^$/d' $1 | grep -i GtkRange-stepper-size | tr -cd '[[:digit:]]'`'"'

echo scrollbar_min_width'=''"'`sed '/scrollbar [{]/!d;s//\n/;s/.*\n//;ta;:a;s/[}].*$//;tb;$!{n;ba};:b;/^$/d' $1 | grep -i GtkRange-slider-width | tr -cd '[[:digit:]]'`

echo scrollbar_button_size'=''"'`sed '/scrollbar [{]/!d;s//\n/;s/.*\n//;ta;:a;s/[}].*$//;tb;$!{n;ba};:b;/^$/d' $1 | grep -i GtkRange-stepper-size | tr -cd '[[:digit:]]'`'"'

echo scale_slider_width'=''"'`sed '/GtkScale [{]/!d;s//\n/;s/.*\n//;ta;:a;s/[}].*$//;tb;$!{n;ba};:b;/^$/d' $1 | grep -i GtkRange-slider-width | tr -cd '[[:digit:]]'`'"'

echo scale_slider_length'=''"'`sed '/GtkScale [{]/!d;s//\n/;s/.*\n//;ta;:a;s/[}].*$//;tb;$!{n;ba};:b;/^$/d' $1 | grep -i GtkScale-slider-length | tr -cd '[[:digit:]]'`'"'

```
USAGE:
script gtk-widgets.css
 @elbullazul please test ambiance based themes what it prints
do now apply some additional bugfixes to it soon. Some bugs can ge fixed on the fly before hand made adjustments are necessary.

**Comment by bluedxca93** [comment]
@iainlane 
slightly improved version of ambiance for 3.20 here:

https://github.com/Elbullazul/Windows-10/files/345200/ambiance-3-20beta-new.zip

**Comment by Elbullazul** [comment]
it's good to see the script progress so well. Thanks for your efforts!

I'll give the newest version a try

**Comment by bluedxca93** [comment]
the notebooks are still wrong fix that soon. ambiance-3-20beta-new.zip
is lastest most complete ambiance version. the script generates
running code, but you better port it with meld by comparing to the
reference theme.

**Comment by iainlane** [comment]
Hi guys, I'm not that sure what this is about - could you explain please? If you've improved Ambiance, it'd be easier for me if you can show me a diff - or possibly check in my version to git and then commit yours on top so I can easily see what changed.

**Comment by bluedxca93** [comment]
@iainlane 
see now
https://github.com/bluedxca93/Ambiance-blx-3-20
second commit is your version and lastest is my current one. Normally you schould be able to esily export that as diff from github.work a little on progressbar and tabs next days.menu padding i do look again soon too.

This 18-20 repo contains just a sed script called port that helps to port 18 themes on 20. goal is to do that as errorless as possible.

**Comment by bluedxca93** [comment]
@iainlane <https://github.com/iainlane>
now fixed progressbar border. The old outcommented code was definitely not
working.Sadly  someone needs now to redraw that one small progressbar
through asset border im so sry.

**Comment by Elbullazul** [comment]
@bluedxca93 actually you can use padding as a workaround too

**Comment by bluedxca93** [comment]
@elbullazul maybe but imagine different padding on progressbar and its trough, arggh better not .
used acceptable assets for now but its better to remake the 2 source  svg files.

**Comment by bluedxca93** [comment]
@iainlane 
notebook design now closeer to gtk2.
please try to find ou why selecting  hovering siomethign on nautilus/nemo draws these white boxes.

**Comment by Elbullazul** [comment]
@bluedxca93 which boxes? can you post a picture?

**Comment by bluedxca93** [comment]
hi,

something
like

item:selected
item:selection.
canvas:selected

well if you select multiple icons it gets white opaque. my previous
fork gets transparent orange too.and that is how it schould be.
notebook tab design now nearly perfect.

**Comment by bluedxca93** [comment]
![bildschirmfoto vom 2016-07-08 17-30-29](https://cloud.githubusercontent.com/assets/4351663/16692661/1893f2e8-4532-11e6-9c31-7f5cf3e0af8d.png)
![bildschirmfoto vom 2016-07-08 17-30-55](https://cloud.githubusercontent.com/assets/4351663/16692663/18a299ec-4532-11e6-8983-3fc7aa664cfc.png)

**Comment by Elbullazul** [comment]
@bluedxca93 it looks nice!

I'll have a look at the error as soon as I can, which may take quite some time

**Comment by bluedxca93** [comment]
@elbullazul thx for your help in advance.  
@iainlane  as you can see some things were redesigned to 2.x look in my mod on github . You can of course modify the borders to look like the older gtk3 ones.Also you can easily design backdrop for progressbar. .primary toolbar is not supported anymore its called toolbar.primary-toolbar and toolbar needs to be defined to as well as headerbar three bars to define at the moment a hell of typing but doing theme entirely in scss won`t let you workaround about that issue easily either. The scroolbar ive stabilized to be usable on cinnamon.

**Comment by bluedxca93** [comment]
@elbullazul iconview gets view thats all the error was about.
found it in my porting script.

**Comment by Elbullazul** [comment]
@bluedxca93 then it's a problem with icon view?

**Comment by bluedxca93** [comment]
(.)iconview is a gtk3 css class. in 3.20+ it gets simply view.

upload this hopefully today on github..

**Comment by Elbullazul** [comment]
new bugs when testing in gtk-3.20 : 

**Text in entry remains as is, whether selected or not**
![screenshot from 2016-09-16 12-42-33](https://cloud.githubusercontent.com/assets/15310985/18602855/54ca65da-7c32-11e6-8427-38dd517dbbf7.png)
### possible fix : ###
```css
entry:selected { background-color } 
OR 
textview:selected { background-color }
```

**Cannot resize windows**
![screenshot from 2016-09-16 12-46-13](https://cloud.githubusercontent.com/assets/15310985/18602856/54cc5c96-7c32-11e6-9afb-98a6200b364b.png)
### possible fix : ###
```css
window-frame { margin } /* has to have some margin in order to be able to resize the window */
```

**Comment by bluedxca93** [comment]
very good idea @elbullazul.
got now a job , well one that has the intendation that i search a new
one.However that does not mean im unable to continue my projects. I do
try to publish some bugfixes today.

**Comment by cinnamoner** [comment]
@bluedxca93 Congratulations for the job. Yeah, I know, finding a job ain't difficult, but finding a job one likes kinda is.

**Comment by bluedxca93** [comment]
@elbullazul fixed now in ambiance-aero. 4 lines slightly differently
form yours but a great step forwards. Any hint on how i do can theme
csd window decoration?

**Comment by Elbullazul** [comment]
@bluedxca93 maybe this?

```css
/* Server-side decoration (SSD) */
.window-frame.ssd {
    border-radius: 0;
    box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.18); 
}

.window-frame.ssd,
.window-frame.ssd:backdrop {
    background-color: @theme_bg_color;
}
```

**Comment by bluedxca93** [comment]
that is 3.18 code.
is the bug in 3.18 too?.

fixed some things in 3.20.
Now it looks different.

any idea of how i can publish theme always with newest version.?

**Comment by Elbullazul** [comment]
the SSD appeared in 3.18
GTK 3.20 uses (for how long?) the same code snippet. That's what I use for my windows 10 theme, and it works perfect

hum, link to the github repo as master.zip file? ex. https://github.com/bluedxca93/aero-experimental/archive/master.zip

**Comment by bluedxca93** [comment]
my version is 20 and its named very differently.

csd is what i themed and there window-frame peoperty got deleted.

it was like that in 3.16-18.

best reference are mate theme changelogs. There are propably even
differences between 3.20  versions and they aren't that small.

**Comment by Elbullazul** [comment]
for CSDs, maybe try this code:

```css
/**********************
 * Window Decorations *
 *********************/
decoration {
  border-radius: 0;
  border-width: 0px;
  box-shadow: 0 3px 9px 1px @osd_bg_color, 0 0 0 1px rgba(0, 0, 0, 0.23);
  margin: 10px; }
  decoration:backdrop {
    box-shadow: 0 3px 9px 1px transparent, 0 2px 6px 2px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.18);
    transition: 200ms ease-out; }
  .maximized decoration, .fullscreen decoration, .tiled decoration {
    border-radius: 0; }
  .popup decoration {
    box-shadow: none; }
  .ssd decoration {
    box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.23); }
  .csd.popup decoration {
    border-radius: 0;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.13); }
  tooltip.csd decoration {
    border-radius: 0;
    box-shadow: none; }
  messagedialog.csd decoration {
    border-radius: 0;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(0, 0, 0, 0.13); }
  .solid-csd decoration {
    margin: 0;
    padding: 4px;
    background-color: @borders;
    border: solid 1px @borders;
    border-radius: 0;
    box-shadow: inset 0 0 0 3px @theme_bg_color, inset 0 1px rgba(255, 255, 255, 0.8); }
    .solid-csd decoration:backdrop {
      box-shadow: inset 0 0 0 3px @theme_bg_color, inset 0 1px rgba(255, 255, 255, 0.8); }
```

BTW, do you mind if I post a link to your theme on my website?

**Comment by bluedxca93** [comment]
if you link to blxgui.blogspot.com too,  no problem at all. if not
write gtk3 theme by bluedxca93.

used slightly different.code now as seen on lastest updates on
ambiance aero.experimental.But this one works too.its even more
corrects

Have you ported the 3.x theme with what?

**Comment by Elbullazul** [comment]
used your porting script.

still lots of fixes to do

**Comment by Elbullazul** [comment]
textview bug solution (partial) found: 

```css
.view:selected:focus, iconview:selected:focus, .view:selected, iconview:selected,
.view text:selected:focus,
iconview text:selected:focus,
textview text:selected:focus,
.view text:selected,
iconview text:selected,
textview text:selected, .view text selection:focus, iconview text selection:focus, .view text selection, iconview text selection,
textview text selection:focus,
textview text selection, flowbox flowboxchild:selected, spinbutton:not(.vertical) selection:focus, spinbutton:not(.vertical) selection,
entry selection:focus,
entry selection, modelbutton.flat:selected, popover.background checkbutton:selected,
popover.background radiobutton:selected,
.menuitem.button.flat:selected, treeview.view:selected:focus, treeview.view:selected, row:selected, calendar:selected {
  background-color: @theme_selected_bg_color;
  color: @theme_selected_fg_color; }
```

**Comment by Elbullazul** [comment]
the missing code to solve the textview bug: 
```css
/* Firefox adress bar */
label.separator {
  color: @theme_fg_color; }
  label.separator:backdrop {
    color: @insensitive_fg_color; }
label selection {
  background-color: @theme_selected_bg_color;
  color: @theme_selected_fg_color; }
label:disabled {
  color: @insensitive_fg_color; }
  label:disabled:backdrop {
    color: shade(@theme_unfocused_fg_color, 1.1); }
label:backdrop {
  color: @insensitive_fg_color; }
```

this fixes the bugs with the firefox adress bar

also, I remarked your script sometimes creates weird nodes, such as scaleprogressbar because the period (.) was removed, but then the class turns out useless since it doesn't exist
